# Generated by Django 3.2.5 on 2021-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipeDetails',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
